### ISSUE TITLE
Last place centering

### ISSUE THREAD

**Issue by cpixl** [farmergreg/vim-lastplace#2]
It would be nice if it was possible to center the line on the screen instead of being at the bottom. Maybe a `zz` would handle it?

**Comment by farmergreg** [comment]
My vim already centers the screen. It might be one of my plugins doing it.... I'll dig deeper in to this later this week. If vim doesn't center it automatically, we will definitely add this feature!

@dan-silva can you double check and see what happens when you jump to the " mark ( type g`" ) inside a large text file? If it doesn't center, I'd also be interested in which version of vim you're running.

Thanks!

**Comment by farmergreg** [comment]
thanks @dan-silva for the great idea! Please try out the new code and let me know how it works for you!

**Comment by cpixl** [comment]
`g`"` only takes me to (apparently) the last line I was when I closed the file, but it doesn't center. `vim --version` gives me this:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2-GNOME GUI. [...]
```

The patch fixed it, it looks nice now :) Thank you!
